services:
  postgres:
    image: postgres:17
    container_name: auction
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sisam
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
